### ISSUE TITLE
Allow using parameters as arguments, not just flags

### ISSUE THREAD

**Issue by wesen** [wesen/sqleton#41]
For example, it would be nicer if the tables argument was arguments:

```yaml
name: count
short: Count the rows in a table
parameters:
  - name: table
    type: string
    default: orders
    help: SQL table to count
query: |
  SELECT COUNT(*) AS `count`
  FROM {{ .table }}
```
